### ISSUE TITLE
Add GPG .asc files to the build process

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-toolbelt#11]
I've been toying with the idea of adding .asc signature files to future releases. I don't have commit access to this repo, so if someone could add me and assign this to me, I'll take a look when time/energy/mood permits.

Thank you.

**Comment by philwareham** [comment]
OK Pete, I've just added you as a user here. Cheers!

**Comment by petecooper** [comment]
Closing this - not necessary for the moment.
