### ISSUE TITLE
Add checks for `diff`-ing duplicated files

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-toolbelt#22]
>Verify that multi-site files such as .htaccess, .htaccess-dist and css.php are up-to-date with their root counterparts.

**Comment by Bloke** [comment]
This would be a boon. It's been forgotten once or twice on release.

**Comment by petecooper** [comment]
We need a shell script on the https://github.com/textpattern/textpattern side to sync the files, I think - the toolbelt should be as read-only as possible against the main repo. I'll open an issue over there.
